### ISSUE TITLE
automatic CPUn block generation

### ISSUE THREAD

**Issue by flAked** [RevoGirl/RevoBoot#18]
More of a suggestion, really.

In the case of the P8P67 at least, processor definition is done in SSDT1 like this: P00n.

Using the automatic CPUn generation would result in duplicate definitions, so it might be a good idea to add a note to AUTOMATIC_PROCESSOR_BLOCK_CREATION that drop & replacing SSDT's is recommended.

**Comment by RevoGirl** [comment]
Thanks. This was why we added _CPU_LABEL_REPLACEMENT. I however don't think that this is an issue (anymore) because we already had plans to simplify some of our directives. And that is what I just did. Have a look at the latest changes. 

Have you seen the new WiKi page where we talk about using a SSDT instead of a modified DSDT?

New installations will now be easier to setup. Even more so when we implement step-4 (adding sleep / wake). Eliminating the need of a modified DSDT so that people won't have to ask for a modified / fixed DSDT anymore... just to setup a new rig.

We'll still be using a static DSDT injection, after everything is working, but this feature is to help people setup their new Sandy Bridge PC's more easily.

**Comment by flAked** [comment]
Ah, yes. Very cool!
That will make a lot of people happy, who are struggling with DSDT edits.

I'll have to make a new tutorial, then :)

**Comment by flAked** [comment]
@label-replacement: from a user perspective who doesn't know much about DSDT and just wants to use the auto generation this isn't very clear in my opinion because he/she must analyse the DSDT/SSDT first to figure that out.

BTW, have you seen any ACPI dumps where the processor definitions were defined in DSDT? Will it cause issues to have duplicate processor definitions with different names? 

Of course this is no issue at all if the user has a SSDT with processor definitions which get dropped.

Looking from the support angle here, a brief look at some ioreg logs and the used RevoBoot settings will resolve this quickly though.

**Comment by RevoGirl** [comment]
They won't have to bother about label replacements. This features was only added so that it can be used, when we need it. Taking care of possible future changes / problems.

The DSDT's I have seen so far (Sandy Bridge) are all loading SSDT tables for it, so we should be fine – we are auto-dropping all SSDT tables from RevoBoot v1.0.19 and onwards. 

Also. You cannot replace anything already in the namespace and thus any addition with the same identifier will simply be ignored.

The most important thing however is to remember that using a stripped down mod DSDT is still the preferred method. Why? 1.) It should be a lot smaller 2.) Should have everything you need it it. But this is for experts only so other people can just use it without having to bother about their DSDT any more though some of it will be moved to the SSDT.

What we are doing here, by introducing this new feature, is to help people get setup in a more straightforward way. Without having to mess with device names and what not. To simply have RevoBoot on a USB-stick and get going the easy way. Without having to use an ultra slow (low Geekbench score) PC because it lacks a proper SMBIOS and ACPI setup for them.
